# Base de datos
db.url=jdbc:mysql://localhost:3306/futbolliveco?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=12345

# APIs externas
api.live.key=1d6ae4f10ab0ecaf154cd1d72d4b2688
api.noticias.key=2bf2f8529c2141db974d043bb0f1af61
api.programados.key=338e17bd886b4996b2c2b6f7def4bce3
api.highlights.key=AIzaSyCLSBUHzaMjlYQEFOMnZp42otPmobUf1Ho

#    https://myaccount.google.com/security
#    https://myaccount.google.com/apppasswords

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=
mail.smtp.password=
mail.from=
